// sampleData.js

const pokemonSeedData = [
	{
		pokemonType: "Fire",
		hp: 60,
		cardName: "Charmander",
		stage: "Basic",
		evolvesFromPokemon: "Bulbasaur",
		expansionCode: 101,
		collectorCardNumber: 1,
	},
	{
		pokemonType: "Electric",
		hp: 55,
		cardName: "Pikachu",
		stage: "Basic",
		evolvesFromPokemon: "Squirtle",
		expansionCode: 102,
		collectorCardNumber: 2,
	},
	{
		pokemonType: "Water",
		hp: 70,
		cardName: "Squirtle",
		stage: "Basic",
		evolvesFromPokemon: "Charmander",
		expansionCode: 103,
		collectorCardNumber: 3,
	},
	{
		pokemonType: "Grass",
		hp: 75,
		cardName: "Bulbasaur",
		stage: "Basic",
		evolvesFromPokemon: "Pikachu",
		expansionCode: 104,
		collectorCardNumber: 4,
	},
	{
		pokemonType: "Psychic",
		hp: 50,
		cardName: "Abra",
		stage: "Basic",
		evolvesFromPokemon: "Meowth",
		expansionCode: 105,
		collectorCardNumber: 5,
	},
	{
		pokemonType: "Fire",
		hp: 80,
		cardName: "Growlithe",
		stage: "Basic",
		evolvesFromPokemon: "Electrode",
		expansionCode: 106,
		collectorCardNumber: 6,
	},
	{
		pokemonType: "Fighting",
		hp: 85,
		cardName: "Machop",
		stage: "Basic",
		evolvesFromPokemon: "Squirtle",
		expansionCode: 107,
		collectorCardNumber: 7,
	},
	{
		pokemonType: "Water",
		hp: 90,
		cardName: "Poliwag",
		stage: "Basic",
		evolvesFromPokemon: "Charmander",
		expansionCode: 108,
		collectorCardNumber: 8,
	},
	{
		pokemonType: "Electric",
		hp: 100,
		cardName: "Electrode",
		stage: "Stage 1",
		evolvesFromPokemon: "Pikachu",
		expansionCode: 109,
		collectorCardNumber: 9,
	},
	{
		pokemonType: "Fire",
		hp: 120,
		cardName: "Arcanine",
		stage: "Stage 2",
		evolvesFromPokemon: "Growlithe",
		expansionCode: 110,
		collectorCardNumber: 10,
	},
	{
		pokemonType: "Fighting",
		hp: 110,
		cardName: "Machoke",
		stage: "Stage 1",
		evolvesFromPokemon: "Machop",
		expansionCode: 111,
		collectorCardNumber: 11,
	},
	{
		pokemonType: "Grass",
		hp: 95,
		cardName: "Ivysaur",
		stage: "Stage 1",
		evolvesFromPokemon: "Bulbasaur",
		expansionCode: 112,
		collectorCardNumber: 12,
	},
	{
		pokemonType: "Electric",
		hp: 130,
		cardName: "Raichu",
		stage: "Stage 2",
		evolvesFromPokemon: "Pikachu",
		expansionCode: 113,
		collectorCardNumber: 13,
	},
	{
		pokemonType: "Water",
		hp: 120,
		cardName: "Wartortle",
		stage: "Stage 1",
		evolvesFromPokemon: "Squirtle",
		expansionCode: 114,
		collectorCardNumber: 14,
	},
	{
		pokemonType: "Fire",
		hp: 135,
		cardName: "Charizard",
		stage: "Stage 2",
		evolvesFromPokemon: "Charmander",
		expansionCode: 115,
		collectorCardNumber: 15,
	},
	{
		pokemonType: "Psychic",
		hp: 150,
		cardName: "Alakazam",
		stage: "Stage 2",
		evolvesFromPokemon: "Abra",
		expansionCode: 116,
		collectorCardNumber: 16,
	},
	{
		pokemonType: "Ghost",
		hp: 60,
		cardName: "Gastly",
		stage: "Basic",
		evolvesFromPokemon: "Pikachu",
		expansionCode: 117,
		collectorCardNumber: 17,
	},
	{
		pokemonType: "Fighting",
		hp: 80,
		cardName: "Mankey",
		stage: "Basic",
		evolvesFromPokemon: "Pidgey",
		expansionCode: 118,
		collectorCardNumber: 18,
	},
	{
		pokemonType: "Fire",
		hp: 90,
		cardName: "Vulpix",
		stage: "Basic",
		evolvesFromPokemon: "Meowth",
		expansionCode: 119,
		collectorCardNumber: 19,
	},
	{
		pokemonType: "Grass",
		hp: 110,
		cardName: "Venusaur",
		stage: "Stage 2",
		evolvesFromPokemon: "Ivysaur",
		expansionCode: 120,
		collectorCardNumber: 20,
	},
	{
		pokemonType: "Water",
		hp: 115,
		cardName: "Blastoise",
		stage: "Stage 2",
		evolvesFromPokemon: "Wartortle",
		expansionCode: 121,
		collectorCardNumber: 21,
	},
	{
		pokemonType: "Electric",
		hp: 60,
		cardName: "Electrike",
		stage: "Basic",
		evolvesFromPokemon: "Squirtle",
		expansionCode: 122,
		collectorCardNumber: 22,
	},
	{
		pokemonType: "Grass",
		hp: 70,
		cardName: "Chikorita",
		stage: "Basic",
		evolvesFromPokemon: "Totodile",
		expansionCode: 123,
		collectorCardNumber: 23,
	},
	{
		pokemonType: "Fire",
		hp: 85,
		cardName: "Cyndaquil",
		stage: "Basic",
		evolvesFromPokemon: "Bulbasaur",
		expansionCode: 124,
		collectorCardNumber: 24,
	},
	{
		pokemonType: "Electric",
		hp: 80,
		cardName: "Pichu",
		stage: "Basic",
		evolvesFromPokemon: "Eevee",
		expansionCode: 125,
		collectorCardNumber: 25,
	},
	{
		pokemonType: "Dragon",
		hp: 120,
		cardName: "Dratini",
		stage: "Basic",
		evolvesFromPokemon: "Zubat",
		expansionCode: 126,
		collectorCardNumber: 26,
	},
	{
		pokemonType: "Electric",
		hp: 130,
		cardName: "Luxray",
		stage: "Stage 2",
		evolvesFromPokemon: "Electrike",
		expansionCode: 127,
		collectorCardNumber: 27,
	},
	{
		pokemonType: "Fire",
		hp: 140,
		cardName: "Blaziken",
		stage: "Stage 2",
		evolvesFromPokemon: "Cyndaquil",
		expansionCode: 128,
		collectorCardNumber: 28,
	},
	{
		pokemonType: "Psychic",
		hp: 130,
		cardName: "Espeon",
		stage: "Stage 1",
		evolvesFromPokemon: "Eevee",
		expansionCode: 129,
		collectorCardNumber: 29,
	},
	{
		pokemonType: "Fighting",
		hp: 90,
		cardName: "Hitmonlee",
		stage: "Stage 1",
		evolvesFromPokemon: "Mankey",
		expansionCode: 130,
		collectorCardNumber: 30,
	},
	{
		pokemonType: "Water",
		hp: 110,
		cardName: "Goldeen",
		stage: "Basic",
		evolvesFromPokemon: "Magikarp",
		expansionCode: 131,
		collectorCardNumber: 31,
	},
	{
		pokemonType: "Fire",
		hp: 120,
		cardName: "Magmar",
		stage: "Basic",
		evolvesFromPokemon: "Snorlax",
		expansionCode: 132,
		collectorCardNumber: 32,
	},
	{
		pokemonType: "Electric",
		hp: 75,
		cardName: "Magnemite",
		stage: "Basic",
		evolvesFromPokemon: "Bulbasaur",
		expansionCode: 133,
		collectorCardNumber: 33,
	},
	{
		pokemonType: "Grass",
		hp: 100,
		cardName: "Lombre",
		stage: "Stage 1",
		evolvesFromPokemon: "Chikorita",
		expansionCode: 134,
		collectorCardNumber: 34,
	},
	{
		pokemonType: "Psychic",
		hp: 85,
		cardName: "Slowpoke",
		stage: "Basic",
		evolvesFromPokemon: "Meowth",
		expansionCode: 135,
		collectorCardNumber: 35,
	},
	{
		pokemonType: "Fighting",
		hp: 100,
		cardName: "Hitmonchan",
		stage: "Stage 1",
		evolvesFromPokemon: "Mankey",
		expansionCode: 136,
		collectorCardNumber: 36,
	},
	{
		pokemonType: "Fire",
		hp: 90,
		cardName: "Houndoom",
		stage: "Stage 2",
		evolvesFromPokemon: "Magmar",
		expansionCode: 137,
		collectorCardNumber: 37,
	},
	{
		pokemonType: "Electric",
		hp: 125,
		cardName: "Raikou",
		stage: "Legendary",
		evolvesFromPokemon: "Pikachu",
		expansionCode: 138,
		collectorCardNumber: 38,
	},
	{
		pokemonType: "Water",
		hp: 150,
		cardName: "Kyogre",
		stage: "Legendary",
		evolvesFromPokemon: "Squirtle",
		expansionCode: 139,
		collectorCardNumber: 39,
	},
	{
		pokemonType: "Dragon",
		hp: 160,
		cardName: "Salamence",
		stage: "Legendary",
		evolvesFromPokemon: "Dratini",
		expansionCode: 140,
		collectorCardNumber: 40,
	},
];

module.exports = pokemonSeedData;
