name: Create Issue and Branch on Task Move

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create a branch with issue title
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE=${{ github.event.issue.title }}
          SANITIZED_TITLE=$(echo "$ISSUE_TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-')
          BRANCH_NAME='feature/issue-${ISSUE_NUMBER}${ISSUE_TITLE// /-}'


          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b $BRANCH_NAME
          git pust origin $BRANCH_NAME 
